### ISSUE TITLE
TickerProviderStateMixin, and others...

### ISSUE THREAD

**Issue by lbarqueira** [MCarlomagno/FlutterMobilenet#12]
Do you ever need the mixin TickerProviderStateMixin?

At Home screen you declare the variable AppLifecycleState _appLifecycleState; where is it used?

Why did you choose a singleton for each "service"? And what about a "normal" class?

Thank you

**Comment by MCarlomagno** [comment]
Hi Luis, thank you very much for your interest, 
**about the TickerProviderStateMixin:**
It's dead code (or "bug"), the main screen had an animation before but then I removed it, and I forgot to remove that portion of code, thank you very much, very attentive of you.

**About the singleton services:**
If I want to access the same variables through different widgets, I create a singleton and "instantiate" it in each widget. There are many ways to solve this using libraries, but I preferred to keep it simple and with as few dependencies as possible

**Comment by lbarqueira** [comment]
Hi, thanks for your explanation.
